/*
 *  Copyright 2025 Readium Foundation. All rights reserved.
 *  Use of this source code is governed by the BSD-style license
 *  available in the top-level LICENSE file of the project.
 */

// DO NOT EDIT. File generated automatically from v2.0.c of the en-US JSON strings.

package org.readium.r2.shared.accessibility

internal val AccessibilityDisplayString.Companion.WAYS_OF_READING_NONVISUAL_READING_ALT_TEXT: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "ways_of_reading_nonvisual_reading_alt_text")
internal val AccessibilityDisplayString.Companion.WAYS_OF_READING_NONVISUAL_READING_NO_METADATA: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "ways_of_reading_nonvisual_reading_no_metadata")
internal val AccessibilityDisplayString.Companion.WAYS_OF_READING_NONVISUAL_READING_NONE: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "ways_of_reading_nonvisual_reading_none")
internal val AccessibilityDisplayString.Companion.WAYS_OF_READING_NONVISUAL_READING_NOT_FULLY: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "ways_of_reading_nonvisual_reading_not_fully")
internal val AccessibilityDisplayString.Companion.WAYS_OF_READING_NONVISUAL_READING_READABLE: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "ways_of_reading_nonvisual_reading_readable")
internal val AccessibilityDisplayString.Companion.WAYS_OF_READING_PRERECORDED_AUDIO_COMPLEMENTARY: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "ways_of_reading_prerecorded_audio_complementary")
internal val AccessibilityDisplayString.Companion.WAYS_OF_READING_PRERECORDED_AUDIO_NO_METADATA: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "ways_of_reading_prerecorded_audio_no_metadata")
internal val AccessibilityDisplayString.Companion.WAYS_OF_READING_PRERECORDED_AUDIO_ONLY: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "ways_of_reading_prerecorded_audio_only")
internal val AccessibilityDisplayString.Companion.WAYS_OF_READING_PRERECORDED_AUDIO_SYNCHRONIZED: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "ways_of_reading_prerecorded_audio_synchronized")
internal val AccessibilityDisplayString.Companion.WAYS_OF_READING_VISUAL_ADJUSTMENTS_MODIFIABLE: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "ways_of_reading_visual_adjustments_modifiable")
internal val AccessibilityDisplayString.Companion.WAYS_OF_READING_VISUAL_ADJUSTMENTS_UNKNOWN: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "ways_of_reading_visual_adjustments_unknown")
internal val AccessibilityDisplayString.Companion.WAYS_OF_READING_VISUAL_ADJUSTMENTS_UNMODIFIABLE: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "ways_of_reading_visual_adjustments_unmodifiable")
internal val AccessibilityDisplayString.Companion.CONFORMANCE_A: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "conformance_a")
internal val AccessibilityDisplayString.Companion.CONFORMANCE_AA: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "conformance_aa")
internal val AccessibilityDisplayString.Companion.CONFORMANCE_AAA: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "conformance_aaa")
internal val AccessibilityDisplayString.Companion.CONFORMANCE_CERTIFIER: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "conformance_certifier")
internal val AccessibilityDisplayString.Companion.CONFORMANCE_CERTIFIER_CREDENTIALS: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "conformance_certifier_credentials")
internal val AccessibilityDisplayString.Companion.CONFORMANCE_DETAILS_CERTIFICATION_INFO: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "conformance_details_certification_info")
internal val AccessibilityDisplayString.Companion.CONFORMANCE_DETAILS_CERTIFIER_REPORT: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "conformance_details_certifier_report")
internal val AccessibilityDisplayString.Companion.CONFORMANCE_DETAILS_CLAIM: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "conformance_details_claim")
internal val AccessibilityDisplayString.Companion.CONFORMANCE_DETAILS_EPUB_ACCESSIBILITY_1_0: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "conformance_details_epub_accessibility_1_0")
internal val AccessibilityDisplayString.Companion.CONFORMANCE_DETAILS_EPUB_ACCESSIBILITY_1_1: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "conformance_details_epub_accessibility_1_1")
internal val AccessibilityDisplayString.Companion.CONFORMANCE_DETAILS_LEVEL_A: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "conformance_details_level_a")
internal val AccessibilityDisplayString.Companion.CONFORMANCE_DETAILS_LEVEL_AA: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "conformance_details_level_aa")
internal val AccessibilityDisplayString.Companion.CONFORMANCE_DETAILS_LEVEL_AAA: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "conformance_details_level_aaa")
internal val AccessibilityDisplayString.Companion.CONFORMANCE_DETAILS_WCAG_2_0: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "conformance_details_wcag_2_0")
internal val AccessibilityDisplayString.Companion.CONFORMANCE_DETAILS_WCAG_2_1: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "conformance_details_wcag_2_1")
internal val AccessibilityDisplayString.Companion.CONFORMANCE_DETAILS_WCAG_2_2: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "conformance_details_wcag_2_2")
internal val AccessibilityDisplayString.Companion.CONFORMANCE_NO: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "conformance_no")
internal val AccessibilityDisplayString.Companion.CONFORMANCE_UNKNOWN_STANDARD: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "conformance_unknown_standard")
internal val AccessibilityDisplayString.Companion.NAVIGATION_INDEX: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "navigation_index")
internal val AccessibilityDisplayString.Companion.NAVIGATION_NO_METADATA: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "navigation_no_metadata")
internal val AccessibilityDisplayString.Companion.NAVIGATION_PAGE_NAVIGATION: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "navigation_page_navigation")
internal val AccessibilityDisplayString.Companion.NAVIGATION_STRUCTURAL: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "navigation_structural")
internal val AccessibilityDisplayString.Companion.NAVIGATION_TOC: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "navigation_toc")
internal val AccessibilityDisplayString.Companion.RICH_CONTENT_ACCESSIBLE_CHEMISTRY_AS_LATEX: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "rich_content_accessible_chemistry_as_latex")
internal val AccessibilityDisplayString.Companion.RICH_CONTENT_ACCESSIBLE_CHEMISTRY_AS_MATHML: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "rich_content_accessible_chemistry_as_mathml")
internal val AccessibilityDisplayString.Companion.RICH_CONTENT_ACCESSIBLE_MATH_AS_LATEX: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "rich_content_accessible_math_as_latex")
internal val AccessibilityDisplayString.Companion.RICH_CONTENT_ACCESSIBLE_MATH_AS_MATHML: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "rich_content_accessible_math_as_mathml")
internal val AccessibilityDisplayString.Companion.RICH_CONTENT_ACCESSIBLE_MATH_DESCRIBED: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "rich_content_accessible_math_described")
internal val AccessibilityDisplayString.Companion.RICH_CONTENT_CLOSED_CAPTIONS: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "rich_content_closed_captions")
internal val AccessibilityDisplayString.Companion.RICH_CONTENT_EXTENDED: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "rich_content_extended")
internal val AccessibilityDisplayString.Companion.RICH_CONTENT_OPEN_CAPTIONS: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "rich_content_open_captions")
internal val AccessibilityDisplayString.Companion.RICH_CONTENT_TRANSCRIPT: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "rich_content_transcript")
internal val AccessibilityDisplayString.Companion.RICH_CONTENT_UNKNOWN: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "rich_content_unknown")
internal val AccessibilityDisplayString.Companion.HAZARDS_FLASHING: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "hazards_flashing")
internal val AccessibilityDisplayString.Companion.HAZARDS_FLASHING_NONE: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "hazards_flashing_none")
internal val AccessibilityDisplayString.Companion.HAZARDS_FLASHING_UNKNOWN: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "hazards_flashing_unknown")
internal val AccessibilityDisplayString.Companion.HAZARDS_MOTION: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "hazards_motion")
internal val AccessibilityDisplayString.Companion.HAZARDS_MOTION_NONE: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "hazards_motion_none")
internal val AccessibilityDisplayString.Companion.HAZARDS_MOTION_UNKNOWN: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "hazards_motion_unknown")
internal val AccessibilityDisplayString.Companion.HAZARDS_NO_METADATA: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "hazards_no_metadata")
internal val AccessibilityDisplayString.Companion.HAZARDS_NONE: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "hazards_none")
internal val AccessibilityDisplayString.Companion.HAZARDS_SOUND: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "hazards_sound")
internal val AccessibilityDisplayString.Companion.HAZARDS_SOUND_NONE: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "hazards_sound_none")
internal val AccessibilityDisplayString.Companion.HAZARDS_SOUND_UNKNOWN: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "hazards_sound_unknown")
internal val AccessibilityDisplayString.Companion.HAZARDS_UNKNOWN: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "hazards_unknown")
internal val AccessibilityDisplayString.Companion.ACCESSIBILITY_SUMMARY_NO_METADATA: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "accessibility_summary_no_metadata")
internal val AccessibilityDisplayString.Companion.ACCESSIBILITY_SUMMARY_PUBLISHER_CONTACT: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "accessibility_summary_publisher_contact")
internal val AccessibilityDisplayString.Companion.LEGAL_CONSIDERATIONS_EXEMPT: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "legal_considerations_exempt")
internal val AccessibilityDisplayString.Companion.LEGAL_CONSIDERATIONS_NO_METADATA: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "legal_considerations_no_metadata")
internal val AccessibilityDisplayString.Companion.ADDITIONAL_ACCESSIBILITY_INFORMATION_ARIA: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "additional_accessibility_information_aria")
internal val AccessibilityDisplayString.Companion.ADDITIONAL_ACCESSIBILITY_INFORMATION_AUDIO_DESCRIPTIONS: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "additional_accessibility_information_audio_descriptions")
internal val AccessibilityDisplayString.Companion.ADDITIONAL_ACCESSIBILITY_INFORMATION_BRAILLE: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "additional_accessibility_information_braille")
internal val AccessibilityDisplayString.Companion.ADDITIONAL_ACCESSIBILITY_INFORMATION_COLOR_NOT_SOLE_MEANS_OF_CONVEYING_INFORMATION: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "additional_accessibility_information_color_not_sole_means_of_conveying_information")
internal val AccessibilityDisplayString.Companion.ADDITIONAL_ACCESSIBILITY_INFORMATION_DYSLEXIA_READABILITY: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "additional_accessibility_information_dyslexia_readability")
internal val AccessibilityDisplayString.Companion.ADDITIONAL_ACCESSIBILITY_INFORMATION_FULL_RUBY_ANNOTATIONS: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "additional_accessibility_information_full_ruby_annotations")
internal val AccessibilityDisplayString.Companion.ADDITIONAL_ACCESSIBILITY_INFORMATION_HIGH_CONTRAST_BETWEEN_FOREGROUND_AND_BACKGROUND_AUDIO: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "additional_accessibility_information_high_contrast_between_foreground_and_background_audio")
internal val AccessibilityDisplayString.Companion.ADDITIONAL_ACCESSIBILITY_INFORMATION_HIGH_CONTRAST_BETWEEN_TEXT_AND_BACKGROUND: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "additional_accessibility_information_high_contrast_between_text_and_background")
internal val AccessibilityDisplayString.Companion.ADDITIONAL_ACCESSIBILITY_INFORMATION_LARGE_PRINT: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "additional_accessibility_information_large_print")
internal val AccessibilityDisplayString.Companion.ADDITIONAL_ACCESSIBILITY_INFORMATION_PAGE_BREAKS: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "additional_accessibility_information_page_breaks")
internal val AccessibilityDisplayString.Companion.ADDITIONAL_ACCESSIBILITY_INFORMATION_RUBY_ANNOTATIONS: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "additional_accessibility_information_ruby_annotations")
internal val AccessibilityDisplayString.Companion.ADDITIONAL_ACCESSIBILITY_INFORMATION_SIGN_LANGUAGE: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "additional_accessibility_information_sign_language")
internal val AccessibilityDisplayString.Companion.ADDITIONAL_ACCESSIBILITY_INFORMATION_TACTILE_GRAPHICS: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "additional_accessibility_information_tactile_graphics")
internal val AccessibilityDisplayString.Companion.ADDITIONAL_ACCESSIBILITY_INFORMATION_TACTILE_OBJECTS: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "additional_accessibility_information_tactile_objects")
internal val AccessibilityDisplayString.Companion.ADDITIONAL_ACCESSIBILITY_INFORMATION_TEXT_TO_SPEECH_HINTING: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "additional_accessibility_information_text_to_speech_hinting")
internal val AccessibilityDisplayString.Companion.ADDITIONAL_ACCESSIBILITY_INFORMATION_ULTRA_HIGH_CONTRAST_BETWEEN_TEXT_AND_BACKGROUND: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "additional_accessibility_information_ultra_high_contrast_between_text_and_background")
internal val AccessibilityDisplayString.Companion.ADDITIONAL_ACCESSIBILITY_INFORMATION_VISIBLE_PAGE_NUMBERING: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "additional_accessibility_information_visible_page_numbering")
internal val AccessibilityDisplayString.Companion.ADDITIONAL_ACCESSIBILITY_INFORMATION_WITHOUT_BACKGROUND_SOUNDS: AccessibilityDisplayString get() = AccessibilityDisplayString(key = "additional_accessibility_information_without_background_sounds")
