package org.readium.r2.navigator.input

import android.view.KeyEvent as AndroidKeyEvent

/**
 * Represents a keyboard event emitted by a navigator.
 *
 * @param type Nature of the event.
 * @param key Key the user pressed or released.
 * @param modifiers Additional input modifiers for keyboard shortcuts.
 * @param characters Characters generated by the keypress, if any.
 */
data class KeyEvent(
    val type: Type,
    val key: Key,
    val modifiers: Set<InputModifier>,
    val characters: String?
) {

    enum class Type {
        Down, Up
    }

    companion object {
        operator fun invoke(type: Type, event: AndroidKeyEvent): KeyEvent? {
            return KeyEvent(
                type = type,
                key = Key(event) ?: return null,
                modifiers = inputModifiers(event),
                characters = event.unicodeChar.toChar().toString()
            )
        }
    }
}

/**
 * Represents a physical key on a keyboard.
 *
 * See https://w3c.github.io/uievents-code/
 */
@JvmInline
value class Key(val code: String) {

    companion object {

        // Alphanumeric section

        val Backquote = Key("Backquote")
        val Backslash = Key("Backslash")
        val BracketLeft = Key("BracketLeft")
        val BracketRight = Key("BracketRight")
        val Comma = Key("Comma")
        val Digit0 = Key("Digit0")
        val Digit1 = Key("Digit1")
        val Digit2 = Key("Digit2")
        val Digit3 = Key("Digit3")
        val Digit4 = Key("Digit4")
        val Digit5 = Key("Digit5")
        val Digit6 = Key("Digit6")
        val Digit7 = Key("Digit7")
        val Digit8 = Key("Digit8")
        val Digit9 = Key("Digit9")
        val Equal = Key("Equal")
        val IntlBackslash = Key("IntlBackslash")
        val IntlRo = Key("IntlRo")
        val IntlYen = Key("IntlYen")
        val KeyA = Key("KeyA")
        val KeyB = Key("KeyB")
        val KeyC = Key("KeyC")
        val KeyD = Key("KeyD")
        val KeyE = Key("KeyE")
        val KeyF = Key("KeyF")
        val KeyG = Key("KeyG")
        val KeyH = Key("KeyH")
        val KeyI = Key("KeyI")
        val KeyJ = Key("KeyJ")
        val KeyK = Key("KeyK")
        val KeyL = Key("KeyL")
        val KeyM = Key("KeyM")
        val KeyN = Key("KeyN")
        val KeyO = Key("KeyO")
        val KeyP = Key("KeyP")
        val KeyQ = Key("KeyQ")
        val KeyR = Key("KeyR")
        val KeyS = Key("KeyS")
        val KeyT = Key("KeyT")
        val KeyU = Key("KeyU")
        val KeyV = Key("KeyV")
        val KeyW = Key("KeyW")
        val KeyX = Key("KeyX")
        val KeyY = Key("KeyY")
        val KeyZ = Key("KeyZ")
        val Minus = Key("Minus")
        val Period = Key("Period")
        val Quote = Key("Quote")
        val Semicolon = Key("Semicolon")
        val Slash = Key("Slash")

        // Function keys

        val AltLeft = Key("AltLeft")
        val AltRight = Key("AltRight")
        val Backspace = Key("Backspace")
        val CapsLock = Key("CapsLock")
        val ContextMenu = Key("ContextMenu")
        val ControlLeft = Key("ControlLeft")
        val ControlRight = Key("ControlRight")
        val Enter = Key("Enter")
        val MetaLeft = Key("MetaLeft")
        val MetaRight = Key("MetaRight")
        val ShiftLeft = Key("ShiftLeft")
        val ShiftRight = Key("ShiftRight")
        val Space = Key("Space")
        val Tab = Key("Tab")

        // Function keys (Japanese and Korean keyboards)

        val Convert = Key("Convert")
        val KanaMode = Key("KanaMode")
        val Lang1 = Key("Lang1")
        val Lang2 = Key("Lang2")
        val Lang3 = Key("Lang3")
        val Lang4 = Key("Lang4")
        val Lang5 = Key("Lang5")
        val NonConvert = Key("NonConvert")

        // Control pad section

        val Delete = Key("Delete")
        val End = Key("End")
        val Help = Key("Help")
        val Home = Key("Home")
        val Insert = Key("Insert")
        val PageDown = Key("PageDown")
        val PageUp = Key("PageUp")

        // Arrow pad section

        val ArrowDown = Key("ArrowDown")
        val ArrowLeft = Key("ArrowLeft")
        val ArrowRight = Key("ArrowRight")
        val ArrowUp = Key("ArrowUp")

        // Numpad section

        val NumLock = Key("NumLock")
        val Numpad0 = Key("Numpad0")
        val Numpad1 = Key("Numpad1")
        val Numpad2 = Key("Numpad2")
        val Numpad3 = Key("Numpad3")
        val Numpad4 = Key("Numpad4")
        val Numpad5 = Key("Numpad5")
        val Numpad6 = Key("Numpad6")
        val Numpad7 = Key("Numpad7")
        val Numpad8 = Key("Numpad8")
        val Numpad9 = Key("Numpad9")
        val NumpadAdd = Key("NumpadAdd")
        val NumpadBackspace = Key("NumpadBackspace")
        val NumpadClear = Key("NumpadClear")
        val NumpadClearEntry = Key("NumpadClearEntry")
        val NumpadComma = Key("NumpadComma")
        val NumpadDecimal = Key("NumpadDecimal")
        val NumpadDivide = Key("NumpadDivide")
        val NumpadEnter = Key("NumpadEnter")
        val NumpadEqual = Key("NumpadEqual")
        val NumpadHash = Key("NumpadHash")
        val NumpadMemoryAdd = Key("NumpadMemoryAdd")
        val NumpadMemoryClear = Key("NumpadMemoryClear")
        val NumpadMemoryRecall = Key("NumpadMemoryRecall")
        val NumpadMemoryStore = Key("NumpadMemoryStore")
        val NumpadMemorySubtract = Key("NumpadMemorySubtract")
        val NumpadMultiply = Key("NumpadMultiply")
        val NumpadParenLeft = Key("NumpadParenLeft")
        val NumpadParenRight = Key("NumpadParenRight")
        val NumpadStar = Key("NumpadStar")
        val NumpadSubtract = Key("NumpadSubtract")

        // Function section

        val Escape = Key("Escape")
        val F1 = Key("F1")
        val F2 = Key("F2")
        val F3 = Key("F3")
        val F4 = Key("F4")
        val F5 = Key("F5")
        val F6 = Key("F6")
        val F7 = Key("F7")
        val F8 = Key("F8")
        val F9 = Key("F9")
        val F10 = Key("F10")
        val F11 = Key("F11")
        val F12 = Key("F12")
        val Fn = Key("Fn")
        val FnLock = Key("FnLock")
        val PrintScreen = Key("PrintScreen")
        val ScrollLock = Key("ScrollLock")
        val Pause = Key("Pause")

        // Media keys

        val BrowserBack = Key("BrowserBack")
        val BrowserFavorites = Key("BrowserFavorites")
        val BrowserForward = Key("BrowserForward")
        val BrowserHome = Key("BrowserHome")
        val BrowserRefresh = Key("BrowserRefresh")
        val BrowserSearch = Key("BrowserSearch")
        val BrowserStop = Key("BrowserStop")
        val Eject = Key("Eject")
        val LaunchApp1 = Key("LaunchApp1")
        val LaunchApp2 = Key("LaunchApp2")
        val LaunchMail = Key("LaunchMail")
        val MediaPlayPause = Key("MediaPlayPause")
        val MediaSelect = Key("MediaSelect")
        val MediaStop = Key("MediaStop")
        val MediaTrackNext = Key("MediaTrackNext")
        val MediaTrackPrevious = Key("MediaTrackPrevious")
        val Power = Key("Power")
        val Sleep = Key("Sleep")
        val AudioVolumeDown = Key("AudioVolumeDown")
        val AudioVolumeMute = Key("AudioVolumeMute")
        val AudioVolumeUp = Key("AudioVolumeUp")
        val WakeUp = Key("WakeUp")

        operator fun invoke(event: AndroidKeyEvent): Key? =
            when (event.keyCode) {
                AndroidKeyEvent.KEYCODE_DEL -> Backspace
                AndroidKeyEvent.KEYCODE_ENTER -> Enter
                AndroidKeyEvent.KEYCODE_FORWARD_DEL -> Delete
                AndroidKeyEvent.KEYCODE_SPACE -> Space
                AndroidKeyEvent.KEYCODE_TAB -> Tab

                AndroidKeyEvent.KEYCODE_0 -> Digit0
                AndroidKeyEvent.KEYCODE_1 -> Digit1
                AndroidKeyEvent.KEYCODE_2 -> Digit2
                AndroidKeyEvent.KEYCODE_3 -> Digit3
                AndroidKeyEvent.KEYCODE_4 -> Digit4
                AndroidKeyEvent.KEYCODE_5 -> Digit5
                AndroidKeyEvent.KEYCODE_6 -> Digit6
                AndroidKeyEvent.KEYCODE_7 -> Digit7
                AndroidKeyEvent.KEYCODE_8 -> Digit8
                AndroidKeyEvent.KEYCODE_9 -> Digit9

                AndroidKeyEvent.KEYCODE_A -> KeyA
                AndroidKeyEvent.KEYCODE_B -> KeyB
                AndroidKeyEvent.KEYCODE_C -> KeyC
                AndroidKeyEvent.KEYCODE_D -> KeyD
                AndroidKeyEvent.KEYCODE_E -> KeyE
                AndroidKeyEvent.KEYCODE_F -> KeyF
                AndroidKeyEvent.KEYCODE_G -> KeyG
                AndroidKeyEvent.KEYCODE_H -> KeyH
                AndroidKeyEvent.KEYCODE_I -> KeyI
                AndroidKeyEvent.KEYCODE_J -> KeyJ
                AndroidKeyEvent.KEYCODE_K -> KeyK
                AndroidKeyEvent.KEYCODE_L -> KeyL
                AndroidKeyEvent.KEYCODE_M -> KeyM
                AndroidKeyEvent.KEYCODE_N -> KeyN
                AndroidKeyEvent.KEYCODE_O -> KeyO
                AndroidKeyEvent.KEYCODE_P -> KeyP
                AndroidKeyEvent.KEYCODE_Q -> KeyQ
                AndroidKeyEvent.KEYCODE_R -> KeyR
                AndroidKeyEvent.KEYCODE_S -> KeyS
                AndroidKeyEvent.KEYCODE_T -> KeyT
                AndroidKeyEvent.KEYCODE_U -> KeyU
                AndroidKeyEvent.KEYCODE_V -> KeyV
                AndroidKeyEvent.KEYCODE_W -> KeyW
                AndroidKeyEvent.KEYCODE_X -> KeyX
                AndroidKeyEvent.KEYCODE_Y -> KeyY
                AndroidKeyEvent.KEYCODE_Z -> KeyZ

                AndroidKeyEvent.KEYCODE_APOSTROPHE -> Quote
                AndroidKeyEvent.KEYCODE_BACKSLASH -> Backslash
                AndroidKeyEvent.KEYCODE_GRAVE -> Backquote
                AndroidKeyEvent.KEYCODE_COMMA -> Comma
                AndroidKeyEvent.KEYCODE_EQUALS -> Equal
                AndroidKeyEvent.KEYCODE_LEFT_BRACKET -> BracketLeft
                AndroidKeyEvent.KEYCODE_MINUS -> Minus
                AndroidKeyEvent.KEYCODE_PERIOD -> Period
                AndroidKeyEvent.KEYCODE_RIGHT_BRACKET -> BracketRight
                AndroidKeyEvent.KEYCODE_SEMICOLON -> Semicolon
                AndroidKeyEvent.KEYCODE_SLASH -> Slash

                AndroidKeyEvent.KEYCODE_NUM_LOCK -> NumLock
                AndroidKeyEvent.KEYCODE_NUMPAD_0 -> Numpad0
                AndroidKeyEvent.KEYCODE_NUMPAD_1 -> Numpad1
                AndroidKeyEvent.KEYCODE_NUMPAD_2 -> Numpad2
                AndroidKeyEvent.KEYCODE_NUMPAD_3 -> Numpad3
                AndroidKeyEvent.KEYCODE_NUMPAD_4 -> Numpad4
                AndroidKeyEvent.KEYCODE_NUMPAD_5 -> Numpad5
                AndroidKeyEvent.KEYCODE_NUMPAD_6 -> Numpad6
                AndroidKeyEvent.KEYCODE_NUMPAD_7 -> Numpad7
                AndroidKeyEvent.KEYCODE_NUMPAD_8 -> Numpad8
                AndroidKeyEvent.KEYCODE_NUMPAD_9 -> Numpad9
                AndroidKeyEvent.KEYCODE_NUMPAD_ADD -> NumpadAdd
                AndroidKeyEvent.KEYCODE_NUMPAD_COMMA -> NumpadComma
                AndroidKeyEvent.KEYCODE_NUMPAD_DIVIDE -> NumpadDivide
                AndroidKeyEvent.KEYCODE_NUMPAD_DOT -> NumpadDecimal
                AndroidKeyEvent.KEYCODE_NUMPAD_ENTER -> NumpadEnter
                AndroidKeyEvent.KEYCODE_NUMPAD_EQUALS -> NumpadEqual
                AndroidKeyEvent.KEYCODE_NUMPAD_LEFT_PAREN -> NumpadParenLeft
                AndroidKeyEvent.KEYCODE_NUMPAD_MULTIPLY -> NumpadMultiply
                AndroidKeyEvent.KEYCODE_NUMPAD_RIGHT_PAREN -> NumpadParenRight
                AndroidKeyEvent.KEYCODE_NUMPAD_SUBTRACT -> NumpadSubtract

                AndroidKeyEvent.KEYCODE_CAPS_LOCK -> CapsLock
                AndroidKeyEvent.KEYCODE_ESCAPE -> Escape
                AndroidKeyEvent.KEYCODE_FUNCTION -> Fn
                AndroidKeyEvent.KEYCODE_INSERT -> Insert

                AndroidKeyEvent.KEYCODE_DPAD_DOWN -> ArrowDown
                AndroidKeyEvent.KEYCODE_DPAD_LEFT -> ArrowLeft
                AndroidKeyEvent.KEYCODE_DPAD_RIGHT -> ArrowRight
                AndroidKeyEvent.KEYCODE_DPAD_UP -> ArrowUp
                AndroidKeyEvent.KEYCODE_HOME -> Home
                AndroidKeyEvent.KEYCODE_PAGE_DOWN -> PageDown
                AndroidKeyEvent.KEYCODE_PAGE_UP -> PageUp

                AndroidKeyEvent.KEYCODE_F1 -> F1
                AndroidKeyEvent.KEYCODE_F2 -> F2
                AndroidKeyEvent.KEYCODE_F3 -> F3
                AndroidKeyEvent.KEYCODE_F4 -> F4
                AndroidKeyEvent.KEYCODE_F5 -> F5
                AndroidKeyEvent.KEYCODE_F6 -> F6
                AndroidKeyEvent.KEYCODE_F7 -> F7
                AndroidKeyEvent.KEYCODE_F8 -> F8
                AndroidKeyEvent.KEYCODE_F9 -> F9
                AndroidKeyEvent.KEYCODE_F10 -> F10
                AndroidKeyEvent.KEYCODE_F11 -> F11
                AndroidKeyEvent.KEYCODE_F12 -> F12

                AndroidKeyEvent.KEYCODE_MEDIA_NEXT -> MediaTrackNext
                AndroidKeyEvent.KEYCODE_MEDIA_PLAY_PAUSE -> MediaPlayPause
                AndroidKeyEvent.KEYCODE_MEDIA_PREVIOUS -> MediaTrackPrevious
                AndroidKeyEvent.KEYCODE_MEDIA_STOP -> MediaStop
                AndroidKeyEvent.KEYCODE_VOLUME_DOWN -> AudioVolumeDown
                AndroidKeyEvent.KEYCODE_VOLUME_MUTE -> AudioVolumeMute
                AndroidKeyEvent.KEYCODE_VOLUME_UP -> AudioVolumeUp

                AndroidKeyEvent.KEYCODE_ALT_LEFT -> AltLeft
                AndroidKeyEvent.KEYCODE_ALT_RIGHT -> AltRight
                AndroidKeyEvent.KEYCODE_CTRL_LEFT -> ControlLeft
                AndroidKeyEvent.KEYCODE_CTRL_RIGHT -> ControlRight
                AndroidKeyEvent.KEYCODE_META_LEFT -> MetaLeft
                AndroidKeyEvent.KEYCODE_META_RIGHT -> MetaRight
                AndroidKeyEvent.KEYCODE_SHIFT_LEFT -> ShiftLeft
                AndroidKeyEvent.KEYCODE_SHIFT_RIGHT -> ShiftRight

                else -> null
            }
    }
}

private fun inputModifiers(event: android.view.KeyEvent): Set<InputModifier> =
    buildSet {
        if (event.isAltPressed) {
            add(InputModifier.Alt)
        }
        if (event.isCtrlPressed) {
            add(InputModifier.Control)
        }
        if (event.isMetaPressed) {
            add(InputModifier.Meta)
        }
        if (event.isShiftPressed) {
            add(InputModifier.Shift)
        }
    }
