name: Navigator

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: 'true'
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build
        run: ./gradlew clean :readium:navigator:build -x test
      - name: Test
        run: ./gradlew :readium:navigator:test --continue

  lint:
    name: Lint
    runs-on: macos-latest
    defaults:
      run:
        working-directory: readium/navigator
    env:
      scripts: ${{ 'src/main/assets/_scripts' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: 'true'
      - name: Install dependencies
        run: npm install --prefix "$scripts"
      - name: Lint JavaScript
        run: yarn --cwd "$scripts" run lint
      - name: Check JavaScript formatting
        run: yarn --cwd "$scripts" run checkformat
      - name: Check if bundled scripts are up-to-date
        run: |
            make scripts
            git diff --exit-code --name-only src/main/assets/readium/scripts

